"""
audit_events.py — the CANONICAL AuditEventType enum.

This is the single source of truth for event names. Add new events HERE first, then use
them. The abbreviated list in docs/SECURITY.md points back to this file.

Reference: ../../feature_plans/audit_trail_plan.md
"""

from enum import Enum


class AuditEventType(str, Enum):
    # ── Authentication ──
    LOGIN = "LOGIN"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    TOKEN_REFRESHED = "TOKEN_REFRESHED"
    MFA_ENABLED = "MFA_ENABLED"
    MFA_VERIFIED = "MFA_VERIFIED"
    MFA_STEP_UP_VERIFIED = "MFA_STEP_UP_VERIFIED"
    MFA_STEP_UP_FAILED = "MFA_STEP_UP_FAILED"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

    # ── User management ──
    USER_CREATED = "USER_CREATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    USER_ACTIVATED = "USER_ACTIVATED"
    ROLE_CHANGED = "ROLE_CHANGED"
    DEPARTMENT_CHANGED = "DEPARTMENT_CHANGED"

    # ── Case management ──
    CASE_CREATED = "CASE_CREATED"
    CASE_ACCESSED = "CASE_ACCESSED"
    CASE_UPDATED = "CASE_UPDATED"
    CASE_CLOSED = "CASE_CLOSED"
    CASE_MEMBER_ADDED = "CASE_MEMBER_ADDED"
    CASE_MEMBER_REMOVED = "CASE_MEMBER_REMOVED"

    # ── Document ──
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_DOWNLOADED = "DOCUMENT_DOWNLOADED"
    DOCUMENT_PREVIEWED = "DOCUMENT_PREVIEWED"
    DOCUMENT_DELETED = "DOCUMENT_DELETED"
    DOCUMENT_RESTORED = "DOCUMENT_RESTORED"
    DOCUMENT_SEARCH_PERFORMED = "DOCUMENT_SEARCH_PERFORMED"

    # ── Signatures ──
    DOCUMENT_SIGNED = "DOCUMENT_SIGNED"
    SIGNATURE_VERIFIED = "SIGNATURE_VERIFIED"
    SIGNATURE_REVOKED = "SIGNATURE_REVOKED"

    # ── Sharing ──
    DOCUMENT_SHARED = "DOCUMENT_SHARED"
    CASE_SHARED = "CASE_SHARED"
    SHARE_LINK_ACCESSED = "SHARE_LINK_ACCESSED"
    SHARE_LINK_PREVIEWED = "SHARE_LINK_PREVIEWED"
    SHARE_LINK_REVOKED = "SHARE_LINK_REVOKED"
    SHARE_LINK_EXPIRED = "SHARE_LINK_EXPIRED"
    SHARE_OTP_SENT = "SHARE_OTP_SENT"

    # ── Security ──
    UNAUTHORIZED_ACCESS_ATTEMPT = "UNAUTHORIZED_ACCESS_ATTEMPT"
    INTEGRITY_VIOLATION = "INTEGRITY_VIOLATION"
    INTEGRITY_CHECK_PASSED = "INTEGRITY_CHECK_PASSED"
    SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY"

    # ── System ──
    SYSTEM_INIT = "SYSTEM_INIT"
    AUDIT_CHAIN_VERIFIED = "AUDIT_CHAIN_VERIFIED"
    AUDIT_CHAIN_BROKEN = "AUDIT_CHAIN_BROKEN"

    # ── Roadmap (playground) ──
    PLAYGROUND_SESSION_STARTED = "PLAYGROUND_SESSION_STARTED"
    PLAYGROUND_SESSION_ENDED = "PLAYGROUND_SESSION_ENDED"
    PLAYGROUND_NOTE_SAVED = "PLAYGROUND_NOTE_SAVED"
