"""
chunk_store.py — physical storage for encrypted chunk objects.
PRAMAAN — Secure Evidence Vault (leet / SIH26)

RESPONSIBILITY:
    put/get/delete the encrypted chunk objects. Everything stored here is ALWAYS ciphertext
    (AES-256-GCM, tag included) — never plaintext. Never has keys. Never has plaintext.

OPAQUE STORAGE KEYS:
    Each chunk is stored under an opaque, random key (secrets.token_hex(16)) generated by
    document_service.py BEFORE calling put_chunk. The key has no structure that reveals the
    document ID, chunk index, or ordering — that information lives only in PostgreSQL
    (document_chunks.storage_key column). A listing of the chunk store therefore reveals nothing
    about document boundaries, chunk order, or document count.

    Old scheme (do not use): {doc_id}/chunk_{index:06d}  — leaked structure
    New scheme: flat namespace, e.g. "a8f13c4d9e2b7f1a"  — opaque

TWO-SERVER TOPOLOGY:
    CHUNK_STORE_BACKEND selects the driver:
      "local" — flat files under CHUNK_STORAGE_DIR  (dev / single-host)
      "sftp"  — paramiko SFTP to CHUNK_STORE_HOST   (Server B in the two-server demo)
    document_service never changes — dispatch is internal to this module.
    Server B has its own OS user (CHUNK_STORE_USER) and SSH key (CHUNK_STORE_KEYFILE).
    It has no database access and no key material.

PUBLIC API (unchanged between backends):
    put_chunk(storage_key: str, data: bytes) -> None
        Write one ciphertext chunk. storage_key is the opaque key from the caller.
    get_chunk(storage_key: str) -> bytes
        Read one ciphertext chunk. Raises FileNotFoundError if missing.
    delete_chunks(storage_keys: list[str]) -> None
        Delete exactly the listed chunks (IDs come from the DB, not from a directory glob).

Reference: feature_plans/chunked_document_storage_plan.md + docs/EDGE_CASES.md §1 & §5.
"""

from __future__ import annotations

import os
from pathlib import Path

from flask import current_app


# ──────────────────────────────────────────────────────────────────
# Internal helpers
# ──────────────────────────────────────────────────────────────────

def _backend() -> str:
    return current_app.config["CHUNK_STORE_BACKEND"]


# ──────────────────────────────────────────────────────────────────
# Local (filesystem) backend
# ──────────────────────────────────────────────────────────────────

def _local_path(storage_key: str) -> str:
    """Flat path: CHUNK_STORAGE_DIR/{storage_key}."""
    if not storage_key or "/" in storage_key or "\\" in storage_key or ".." in storage_key:
        raise ValueError("invalid storage_key")
    return str(Path(current_app.config["CHUNK_STORAGE_DIR"]) / storage_key)


def _put_local(storage_key: str, data: bytes) -> None:
    """Write ciphertext to CHUNK_STORAGE_DIR/{storage_key}."""
    path = Path(_local_path(storage_key))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def _get_local(storage_key: str) -> bytes:
    """Read ciphertext from CHUNK_STORAGE_DIR/{storage_key}."""
    path = Path(_local_path(storage_key))
    if not path.is_file():
        raise FileNotFoundError(storage_key)
    return path.read_bytes()


def _delete_local(storage_keys: list[str]) -> None:
    """Delete each file at CHUNK_STORAGE_DIR/{key}. Idempotent."""
    for key in storage_keys:
        try:
            os.unlink(_local_path(key))
        except FileNotFoundError:
            continue
        except ValueError:
            continue


# ──────────────────────────────────────────────────────────────────
# SFTP backend (Server B — two-server demo)
# ──────────────────────────────────────────────────────────────────
# Uses paramiko with SSH key auth (no passwords). The app connects as
# CHUNK_STORE_USER to CHUNK_STORE_HOST using CHUNK_STORE_KEYFILE.
# Server B has no DB access and no key material.

def _put_sftp(storage_key: str, data: bytes) -> None:
    """Upload ciphertext via SFTP to Server B. TODO (paramiko, key auth)."""
    raise NotImplementedError


def _get_sftp(storage_key: str) -> bytes:
    """Download ciphertext from Server B via SFTP. TODO."""
    raise NotImplementedError


def _delete_sftp(storage_keys: list[str]) -> None:
    """Delete chunks from Server B via SFTP. TODO."""
    raise NotImplementedError


# ──────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────

def put_chunk(storage_key: str, data: bytes) -> None:
    """Write one ciphertext chunk under the given opaque storage_key.
    storage_key must be generated by the caller (secrets.token_hex(16)).
    data must be AES-256-GCM ciphertext (tag included) — never plaintext.
    """
    if _backend() == "local":
        return _put_local(storage_key, data)
    if _backend() == "sftp":
        return _put_sftp(storage_key, data)
    raise ValueError(f"unknown chunk store backend: {_backend()!r}")


def get_chunk(storage_key: str) -> bytes:
    """Read one ciphertext chunk. Raises FileNotFoundError if the key is missing."""
    if _backend() == "local":
        return _get_local(storage_key)
    if _backend() == "sftp":
        return _get_sftp(storage_key)
    raise ValueError(f"unknown chunk store backend: {_backend()!r}")


def delete_chunks(storage_keys: list[str]) -> None:
    """Delete exactly the chunks identified by storage_keys.
    Keys come from the DB (document_chunks.storage_key), never from a directory glob.
    Idempotent — missing keys are silently ignored.
    """
    if _backend() == "local":
        return _delete_local(storage_keys)
    if _backend() == "sftp":
        return _delete_sftp(storage_keys)
    raise ValueError(f"unknown chunk store backend: {_backend()!r}")
